### 🟢 Valid
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "username": "test",
  "password": "Pa$$word123"
}

### 🚫 Invalid
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "username": "test6",
  "password": "Pa$$word123!"
}

### 🚫 Invalid
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "password": "Pa$$word123"
}

### 🚫 Invalid
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "username": "hjwgew3heikwoj"
}

### 🚫 Invalid
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  
}