### POST => Create new task
# 🟢 Valid
POST http://localhost:3000/tasks
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QyIiwiaWF0IjoxNjU1NDE0NjA2LCJleHAiOjE2NTU0MTgyMDZ9.1d7AjjOGpQYJ6mEQQjz9JRg4OsElW4w3GToFGBN_xwE

{
  "title": "Do shopping",
  "description": "Go to the mall and buy clothes and shoes"
}

### 🟢 Valid
POST http://localhost:3000/tasks
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QyIiwiaWF0IjoxNjU1NDE2MDE1LCJleHAiOjE2NTU0MTk2MTV9.MEtEUvCZtNepLz6Xves-OF2YOPxh0_MHEqQmvGeHfYo

{
  "title": "Testing",
  "description": "buy milk from the Grocery Store"
}

### 🟢 Valid
POST http://localhost:3000/tasks
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QyIiwiaWF0IjoxNjU1NDE0MjM1LCJleHAiOjE2NTU0MTc4MzV9.CRvpkMjGAexl2u2t1r4BzBYVFX-IEbaRWK2gm7TZo_M

{
  "title": "Clean roon",
  "description": "Completely clean my room"
}


### 🚫 Invalid
POST http://localhost:3000/tasks
Content-Type: application/json

{
  "title": "Go hiking",
  "description": "Hike in the forest"
}

### 🚫 Invalid
POST http://localhost:3000/tasks
Content-Type: application/json

{
}