### POST => Create new task
# 🟢 Valid
POST http://localhost:3000/tasks
Content-Type: application/json

{
  "title": "Go hiking",
  "description": "Hike in the forest"
}

### 🟢 Valid
POST http://localhost:3000/tasks
Content-Type: application/json

{
  "title": "Testing",
  "description": "buy milk from the Grocery Store"
}

### 🟢 Valid
POST http://localhost:3000/tasks
Content-Type: application/json

{
  "title": "Clean roon",
  "description": "Completely clean my room"
}


### 🚫 Invalid
POST http://localhost:3000/tasks
Content-Type: application/json

{
}