### DELETE => Delete task by id
# 🟢 Valid
DELETE http://localhost:3000/tasks/e04e4b85-b6df-4810-8910-60615769a4a1


### DELETE => Delete task by id
# 🚫 Invalid
DELETE http://localhost:3000/tasks/invalid