### PATCH => Create new task
# 🟢 Valid
PATCH http://localhost:3000/tasks/8b8e97e3-9ada-4ed7-a5bf-abe1967c2749/status
Content-Type: application/json

{
  "status": "IN_PROGRESS"
}


### 🚫 Invalid
PATCH http://localhost:3000/tasks/invalid-id-goes-here/status
Content-Type: application/json

{
}