### PATCH => Create new task
# 🟢 Valid
PATCH http://localhost:3000/tasks/dccaed51-9c84-4cac-84fa-bec5e65031b9/status
Content-Type: application/json

{
  "status": "IN_PROGRESS"
}


### 🚫 Invalid
PATCH http://localhost:3000/tasks/dccaed51-9c84-4cac-84fa-bec5e65031b0/status
Content-Type: application/json

{
}